spring.application.name=Sri-Laxmi-Mobiles

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=${PORT:8081}

# =========================================================
# WHATSAPP CLOUD API
# =========================================================

WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID:}

WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:}

WHATSAPP_OWNER_NUMBER=${WHATSAPP_OWNER_NUMBER:}

WHATSAPP_API_VERSION=${WHATSAPP_API_VERSION:v21.0}